### ISSUE TITLE
error "Specified time is not representable"

### ISSUE THREAD

**Issue by willtm** [phfrohring/org-to-blog#1]
Hello,

I'm interested in your project and wanted to give it a try.  I followed your instructions and encountered an error (see full text below) after attempting `M-x blog-generate`.  I'm not that proficient in elisp but I think that the code in `org-to-blog.el` below may have something to do with the problem I'm encountering.

As you can see in the backtrace, the time stamp `<0001-01-01>` is not "representable".  I think this elisp in `org-to-blog.el` may be related but I'm not sure.

`
         (setq entry_index (1+ entry_index))
         (setq entry_index_str (number-to-string entry_index))
         (org-set-property
          "EXPORT_DATE"
          (concat
           "<"
           (concat (make-string (- 4 (length entry_index_str)) ?0) entry_index_str)
           "-01-01>"))
`

The full text of the backtrace:

`
Debugger entered--Lisp error: (error "Specified time is not representable")
  encode-time(0 0 0 1 1 1)
  org-element-timestamp-interpreter((timestamp (:type active :raw-value "<0001-01-01>" :year-start 1 :month-start 1 :day-start 1 :hour-start nil :minute-start nil :year-end 1 :month-end 1 :day-end 1 :hour-end nil :minute-end nil :begin 1 :end 13 :post-blank 0 :parent (#0))) nil)
  org-element--interpret-data-1((timestamp (:type active :raw-value "<0001-01-01>" :year-start 1 :month-start 1 :day-start 1 :hour-start nil :minute-start nil :year-end 1 :month-end 1 :day-end 1 :hour-end nil :minute-end nil :begin 1 :end 13 :post-blank 0 :parent (#0))) nil)
  #[(obj) "\302	\"\207" [obj parent org-element--interpret-data-1] 3]((timestamp (:type active :raw-value "<0001-01-01>" :year-start 1 :month-start 1 :day-start 1 :hour-start nil :minute-start nil :year-end 1 :month-end 1 :day-end 1 :hour-end nil :minute-end nil :begin 1 :end 13 :post-blank 0 :parent (#0))))
  mapconcat(#[(obj) "\302	\"\207" [obj parent org-element--interpret-data-1] 3] ((timestamp (:type active :raw-value "<0001-01-01>" :year-start 1 :month-start 1 :day-start 1 :hour-start nil :minute-start nil :year-end 1 :month-end 1 :day-end 1 :hour-end nil :minute-end nil :begin 1 :end 13 :post-blank 0 :parent #0))) "")
  org-element--interpret-data-1(((timestamp (:type active :raw-value "<0001-01-01>" :year-start 1 :month-start 1 :day-start 1 :hour-start nil :minute-start nil :year-end 1 :month-end 1 :day-end 1 :hour-end nil :minute-end nil :begin 1 :end 13 :post-blank 0 :parent #0))) nil)
  org-element-interpret-data(((timestamp (:type active :raw-value "<0001-01-01>" :year-start 1 :month-start 1 :day-start 1 :hour-start nil :minute-start nil :year-end 1 :month-end 1 :day-end 1 :hour-end nil :minute-end nil :begin 1 :end 13 :post-blank 0 :parent #0))))
  org-export-as(html t nil nil (:output-file "c:/Users/Will/Temporary/website/first_post!.html"))
  org-export-to-file(html "c:/Users/Will/Temporary/website/first_post!.html" nil t nil nil nil)
  org-html-export-to-html(nil t)
  (let ((heading-begin-pos (point)) (heading-end-pos (blog-get_end_entry_pos)) (entry_id "")) (goto-char heading-begin-pos) (setq entry_id (blog-get_entry_id)) (save-excursion (blog-reroot_file_links heading-end-pos)) (save-excursion (blog-reroot_internal_links heading-end-pos)) (org-set-property "EXPORT_FILE_NAME" (expand-file-name entry_id blog-website_path)) (setq entry_index (1+ entry_index)) (setq entry_index_str (number-to-string entry_index)) (org-set-property "EXPORT_DATE" (concat "<" (concat (make-string (- 4 (length entry_index_str)) 48) entry_index_str) "-01-01>")) (org-html-export-to-html nil t) (org-delete-property "EXPORT_FILE_NAME"))
  (lambda nil (let ((heading-begin-pos (point)) (heading-end-pos (blog-get_end_entry_pos)) (entry_id "")) (goto-char heading-begin-pos) (setq entry_id (blog-get_entry_id)) (save-excursion (blog-reroot_file_links heading-end-pos)) (save-excursion (blog-reroot_internal_links heading-end-pos)) (org-set-property "EXPORT_FILE_NAME" (expand-file-name entry_id blog-website_path)) (setq entry_index (1+ entry_index)) (setq entry_index_str (number-to-string entry_index)) (org-set-property "EXPORT_DATE" (concat "<" (concat (make-string (- 4 (length entry_index_str)) 48) entry_index_str) "-01-01>")) (org-html-export-to-html nil t) (org-delete-property "EXPORT_FILE_NAME")))()
  funcall((lambda nil (let ((heading-begin-pos (point)) (heading-end-pos (blog-get_end_entry_pos)) (entry_id "")) (goto-char heading-begin-pos) (setq entry_id (blog-get_entry_id)) (save-excursion (blog-reroot_file_links heading-end-pos)) (save-excursion (blog-reroot_internal_links heading-end-pos)) (org-set-property "EXPORT_FILE_NAME" (expand-file-name entry_id blog-website_path)) (setq entry_index (1+ entry_index)) (setq entry_index_str (number-to-string entry_index)) (org-set-property "EXPORT_DATE" (concat "<" (concat (make-string (- 4 (length entry_index_str)) 48) entry_index_str) "-01-01>")) (org-html-export-to-html nil t) (org-delete-property "EXPORT_FILE_NAME"))))
  (save-excursion (funcall func))
  (progn (beginning-of-line) (save-excursion (funcall func)) (end-of-line))
  (if (and (search-forward-regexp "^* " nil "end") (member blog-heading_tag (split-string (or (cdr (assoc "TAGS" (org-entry-properties))) "") ":" t))) (progn (beginning-of-line) (save-excursion (funcall func)) (end-of-line)))
  (while (< (point) (point-max)) (if (and (search-forward-regexp "^* " nil "end") (member blog-heading_tag (split-string (or (cdr (assoc "TAGS" ...)) "") ":" t))) (progn (beginning-of-line) (save-excursion (funcall func)) (end-of-line))))
  (progn (org-mode) (insert-file-contents blog-main) (goto-char (point-min)) (while (< (point) (point-max)) (if (and (search-forward-regexp "^* " nil "end") (member blog-heading_tag (split-string (or (cdr ...) "") ":" t))) (progn (beginning-of-line) (save-excursion (funcall func)) (end-of-line)))))
  (unwind-protect (progn (org-mode) (insert-file-contents blog-main) (goto-char (point-min)) (while (< (point) (point-max)) (if (and (search-forward-regexp "^* " nil "end") (member blog-heading_tag (split-string (or ... "") ":" t))) (progn (beginning-of-line) (save-excursion (funcall func)) (end-of-line))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (org-mode) (insert-file-contents blog-main) (goto-char (point-min)) (while (< (point) (point-max)) (if (and (search-forward-regexp "^* " nil "end") (member blog-heading_tag (split-string ... ":" t))) (progn (beginning-of-line) (save-excursion (funcall func)) (end-of-line))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (org-mode) (insert-file-contents blog-main) (goto-char (point-min)) (while (< (point) (point-max)) (if (and (search-forward-regexp "^* " nil "end") (member blog-heading_tag ...)) (progn (beginning-of-line) (save-excursion ...) (end-of-line))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  blog-map_entries("c:/Users/Will/Temporary/blog.org" (lambda nil (let ((heading-begin-pos (point)) (heading-end-pos (blog-get_end_entry_pos)) (entry_id "")) (goto-char heading-begin-pos) (setq entry_id (blog-get_entry_id)) (save-excursion (blog-reroot_file_links heading-end-pos)) (save-excursion (blog-reroot_internal_links heading-end-pos)) (org-set-property "EXPORT_FILE_NAME" (expand-file-name entry_id blog-website_path)) (setq entry_index (1+ entry_index)) (setq entry_index_str (number-to-string entry_index)) (org-set-property "EXPORT_DATE" (concat "<" (concat (make-string (- 4 (length entry_index_str)) 48) entry_index_str) "-01-01>")) (org-html-export-to-html nil t) (org-delete-property "EXPORT_FILE_NAME"))))
  (let ((entry_index 0) (entry_index_str "") (html_files (directory-files blog-website_path t ".*\\.html"))) (mapc (function (lambda (html_file) (delete-file html_file))) html_files) (blog-map_entries blog-main (function (lambda nil (let ((heading-begin-pos (point)) (heading-end-pos (blog-get_end_entry_pos)) (entry_id "")) (goto-char heading-begin-pos) (setq entry_id (blog-get_entry_id)) (save-excursion (blog-reroot_file_links heading-end-pos)) (save-excursion (blog-reroot_internal_links heading-end-pos)) (org-set-property "EXPORT_FILE_NAME" (expand-file-name entry_id blog-website_path)) (setq entry_index (1+ entry_index)) (setq entry_index_str (number-to-string entry_index)) (org-set-property "EXPORT_DATE" (concat "<" (concat ... entry_index_str) "-01-01>")) (org-html-export-to-html nil t) (org-delete-property "EXPORT_FILE_NAME"))))))
  blog-map_entries_to_html_files()
  blog-org_to_www()
  blog-generate()
  funcall-interactively(blog-generate)
  call-interactively(blog-generate record nil)
  command-execute(blog-generate record)
  #[257 "\304\305!\203\f
`

Do you have any suggestions for a next step in the troubleshooting process?

**Comment by phfrohring** [comment]
Hello,

This code was used to order blog post when using `ox-publish`, was removed in this commit fd829e2.
Also updated Readme so that it's easier to test.

Is it working for you?

**Comment by willtm** [comment]
Just downloaded and re-evaluated the new `org-to-blog.el`.  I received the following error:

`
Debugger entered--Lisp error: (void-variable find_duplicates)
  (funcall find_duplicates (cdr list) dups)
  (let* ((head (car list)) (rest (cdr list)) (cur (car rest)) (found nil)) (while (and (not found) rest) (setq cur (car rest)) (if (string= head cur) (progn (setq found t) (setq dups (cons head dups)))) (setq rest (cdr rest))) (funcall find_duplicates (cdr list) dups))
  (if (not (cdr list)) dups (let* ((head (car list)) (rest (cdr list)) (cur (car rest)) (found nil)) (while (and (not found) rest) (setq cur (car rest)) (if (string= head cur) (progn (setq found t) (setq dups (cons head dups)))) (setq rest (cdr rest))) (funcall find_duplicates (cdr list) dups)))
  (closure ((list "second_post" "first_post!") t) (list dups) (if (not (cdr list)) dups (let* ((head (car list)) (rest (cdr list)) (cur (car rest)) (found nil)) (while (and (not found) rest) (setq cur (car rest)) (if (string= head cur) (progn (setq found t) (setq dups (cons head dups)))) (setq rest (cdr rest))) (funcall find_duplicates (cdr list) dups))))(("second_post" "first_post!") nil)
  funcall((closure ((list "second_post" "first_post!") t) (list dups) (if (not (cdr list)) dups (let* ((head (car list)) (rest (cdr list)) (cur (car rest)) (found nil)) (while (and (not found) rest) (setq cur (car rest)) (if (string= head cur) (progn (setq found t) (setq dups (cons head dups)))) (setq rest (cdr rest))) (funcall find_duplicates (cdr list) dups)))) ("second_post" "first_post!") nil)
  (let ((dups nil) (find_duplicates (function (lambda (list dups) (if (not (cdr list)) dups (let* (... ... ... ...) (while ... ... ... ...) (funcall find_duplicates ... dups))))))) (funcall find_duplicates list dups))
  blog-find_duplicates(("second_post" "first_post!"))
  (setq dups (blog-find_duplicates ids))
  (let ((ids nil) (dups nil) (missing-files nil)) (setq blog-heading_id_custom_id nil) (setq blog-assets nil) (blog-map_entries blog-main (function (lambda nil (let ((heading-begin-pos (point)) (heading-end-pos (blog-get_end_entry_pos)) (entry_id "") (entry_name "") (custom_id "")) (goto-char heading-begin-pos) (setq entry_name (blog-get_entry_name)) (setq entry_id (blog-get_entry_id)) (setq custom_id (org-entry-get (point) "CUSTOM_ID")) (setq ids (cons entry_id ids)) (setq blog-heading_id_custom_id (cons (list custom_id ... entry_id entry_name) blog-heading_id_custom_id)) (save-excursion (blog-map_file_links heading-end-pos (function ...))))))) (setq missing-files (cl-remove-if (function (lambda (file_name) (file-exists-p (concat blog-main_data "/" file_name)))) blog-assets)) (if missing-files (progn (error (concat "Blog points to not existing files: " (format "%s" missing-files))))) (setq dups (blog-find_duplicates ids)) (if dups (progn (error (concat "Entries is not a set. Duplicates: " (format "%s" dups))))))
  blog-check_blog()
  blog-org_to_www()
  blog-generate()
  funcall-interactively(blog-generate)
  call-interactively(blog-generate record nil)
  command-execute(blog-generate record)
  #[257 "\304\305!\203\f
`

**Comment by phfrohring** [comment]
Tested the code, working for me. 
Maybe be a difference in setup?
Here is what I've got:

```
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-17
Org-mode version 8.3.6 (8.3.6-7-g4d7d52-elpa @ /Users/nomos/.emacs.d/elpa/org-20161010/)
```

**Comment by willtm** [comment]
I'm running Windows 10.  My Emacs init has been running very well for a long time.  Can't see any reason why it wouldn't work.  But Emacs is always providing me with opportunities to learn!

`
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17
Org-mode version 8.3.6 (8.3.6-7-g4d7d52-elpa @ c:/Users/Will/.emacs.d/elpa/org-20161010/)
`

**Comment by phfrohring** [comment]
I have re-implemented and tested "find_duplicates" using `cl-labels`.
I could not reproduce the bug because of how my code is evaluated:
  `-*- lexical-binding: t -*-` has an effect if on first commented line i.e. `;;;  -*- lexical-binding: t -*-`
  this particular code in tangled from a file to an other then evaluated...
  ... so `-*- lexical-binding: t -*-` does not have an effect at evaluation time!

commit: c2c5c32

Would you test it?

Thx!

**Comment by willtm** [comment]
That did the trick!  It worked just fine.  Thank you.

**Comment by phfrohring** [comment]
👍
